# sc_named_colors(<output_dir>)
# Writes <output_dir>/named_colors.inc: the CSS named colours as {"name", {r, g, b}}, lines, for
# sc::color's table. The list comes from the named-color table in CSS Color Module Level 4
# (https://www.w3.org/TR/css-color-4/#named-colors), read from the spec's source at the head of
# the CSS working group's repository - one file, not the whole repository.
#
# It is downloaded at configure time, at most once a day (SC_NAMED_COLORS_MAX_AGE seconds; 0
# checks on every configure). In between, and when the download or parsing fails (which also
# waits a day before trying again), the last good list is kept. With no list yet and no network,
# src/named_colors.inc - the committed copy - is used. To refresh that copy, configure, then:
#   cp <build>/generated/named_colors.inc src/named_colors.inc
set(SC_NAMED_COLORS_URL "https://raw.githubusercontent.com/w3c/csswg-drafts/main/css-color-4/Overview.bs"
    CACHE STRING "Source of the CSS named colours: the CSS Color 4 spec source")
set(SC_NAMED_COLORS_MAX_AGE 86400 CACHE STRING "Seconds before the CSS named colours are checked again")

function(sc_named_colors output_dir)
    set(output "${output_dir}/named_colors.inc")
    set(stamp "${output_dir}/named_colors.checked")
    set(fallback "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../src/named_colors.inc")

    string(TIMESTAMP now "%s" UTC)
    if (EXISTS "${output}" AND EXISTS "${stamp}")
        file(TIMESTAMP "${stamp}" checked "%s" UTC)
        math(EXPR age "${now} - ${checked}")
        if (age LESS SC_NAMED_COLORS_MAX_AGE)
            return()
        endif ()
    endif ()

    set(spec "${output_dir}/css-color-4.bs")
    file(DOWNLOAD "${SC_NAMED_COLORS_URL}" "${spec}" TIMEOUT 15 STATUS status)
    list(GET status 0 status_code)
    set(colors "")
    set(count 0)
    if (status_code EQUAL 0)
        # One table row per colour: <dfn>aliceblue</dfn><td>#f0f8ff<td>240 248 255
        file(STRINGS "${spec}" rows REGEX "<dfn>[a-z]+</dfn><td>#[0-9a-fA-F]+<td>[0-9]+ [0-9]+ [0-9]+")
        foreach (row IN LISTS rows)
            string(REGEX MATCH "<dfn>([a-z]+)</dfn><td>#[0-9a-fA-F]+<td>([0-9]+) ([0-9]+) ([0-9]+)" _ "${row}")
            string(APPEND colors "{\"${CMAKE_MATCH_1}\", {${CMAKE_MATCH_2}, ${CMAKE_MATCH_3}, ${CMAKE_MATCH_4}}},\n")
            math(EXPR count "${count} + 1")
        endforeach ()
    endif ()
    file(REMOVE "${spec}")

    if (count GREATER_EQUAL 140) # CSS has had 148 since 2014; far fewer means the format changed
        # Rewritten only when the list changes, so color.cpp isn't recompiled for nothing.
        file(CONFIGURE OUTPUT "${output}" CONTENT
             "// CSS named colours from ${SC_NAMED_COLORS_URL}\n// Generated by cmake/NamedColors.cmake - do not edit.\n${colors}" @ONLY)
        message(STATUS "CSS named colours: ${count}, checked against the CSS Color 4 spec")
    elseif (EXISTS "${output}")
        message(STATUS "CSS named colours: couldn't check the spec (${status}), keeping the last list")
    else ()
        configure_file("${fallback}" "${output}" COPYONLY)
        message(STATUS "CSS named colours: couldn't check the spec (${status}), using src/named_colors.inc")
    endif ()
    # A failed check counts too: offline, configuring shouldn't wait on the timeout every time.
    file(TOUCH "${stamp}")
endfunction()
